### ISSUE TITLE
Add optional `font-smoothing` properties

### ISSUE THREAD

**Issue by stormwarning** [stormwarning/typeset.css#19]
``` scss
//
// Fonts on OS X will look more consistent with other systems that do not
// render text using sub-pixel anti-aliasing.
//
html {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```
